<a href="https://colab.research.google.com/github/razaool/ML_Housing/blob/main/housingdata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df_house_price = pd.read_excel('/content/kaggle_london_house_price_data.xlsx')

In [ ]:
display(df_house_price.head())
display(df_house_price.info())

,fullAddress,postcode,country,outcode,bathrooms,bedrooms,floorAreaSqM,livingRooms,tenure,propertyType,currentEnergyRating,history_date,history_price
0,"1 Abbess Close, London, E6 5TX",E6 5TX,England,E6,2.0,4.0,138.0,1.0,Freehold,End Terrace House,C,2023-02-17,420000
1,"1 Abbey Gardens, Southwark Park Road, London, ...",SE16 3RQ,England,SE16,1.0,1.0,41.0,1.0,Freehold,End Terrace House,D,2020-01-29,355000
2,"1 Academia Way, London, N17 8HE",N17 8HE,England,N17,NaN,NaN,77.0,NaN,Leasehold,Purpose Built Flat,C,2022-05-17,155000
3,"1 Acorn Terrace, Archway Road, London, N6 4BF",N6 4BF,England,N6,1.0,4.0,115.0,1.0,Freehold,End Terrace House,C,2022-03-18,830000
4,"1 Adam Court, Opal Street, London, SE11 4HP",SE11 4HP,England,SE11,1.0,3.0,85.0,1.0,Leasehold,Flat/Maisonette,D,2023-05-09,475000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137760 entries, 0 to 137759
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fullAddress          137760 non-null  object
 1   postcode             137760 non-null  object
 2   country              137760 non-null  object
 3   outcode              137760 non-null  object
 4   bathrooms            105516 non-null  float64
 5   bedrooms             118795 non-null  float64
 6   floorAreaSqM         127594 non-null  float64
 7   livingRooms          111129 non-null  float64
 8   tenure               132446 non-null  object
 9   propertyType         137244 non-null  object
 10  currentEnergyRating  110580 non-null  object
 11  history_date         137760 non-null  datetime64[ns]
 12  history_price        137760 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 13.7+ MB

None

In [ ]:
columns_to_impute = ['bathrooms', 'bedrooms', 'livingRooms']

for col in columns_to_impute:
    median_value = df_house_price[col].median()
    df_house_price[col] = df_house_price[col].fillna(round(median_value))

display(df_house_price.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137760 entries, 0 to 137759
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fullAddress          137760 non-null  object
 1   postcode             137760 non-null  object
 2   country              137760 non-null  object
 3   outcode              137760 non-null  object
 4   bathrooms            137760 non-null  float64
 5   bedrooms             137760 non-null  float64
 6   floorAreaSqM         127594 non-null  float64
 7   livingRooms          137760 non-null  float64
 8   tenure               132446 non-null  object
 9   propertyType         137244 non-null  object
 10  currentEnergyRating  110580 non-null  object
 11  history_date         137760 non-null  datetime64[ns]
 12  history_price        137760 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 13.7+ MB

None

In [ ]:
df_house_price.dropna(subset=['floorAreaSqM'], inplace=True)
display(df_house_price.info())

<class 'pandas.core.frame.DataFrame'>
Index: 127594 entries, 0 to 137759
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fullAddress          127594 non-null  object
 1   postcode             127594 non-null  object
 2   country              127594 non-null  object
 3   outcode              127594 non-null  object
 4   bathrooms            127594 non-null  float64
 5   bedrooms             127594 non-null  float64
 6   floorAreaSqM         127594 non-null  float64
 7   livingRooms          127594 non-null  float64
 8   tenure               124020 non-null  object
 9   propertyType         127590 non-null  object
 10  currentEnergyRating  107339 non-null  object
 11  history_date         127594 non-null  datetime64[ns]
 12  history_price        127594 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 13.6+ MB

None

In [ ]:
# Calculate the mean history_price for each outcode
outcode_price_mean = df_house_price_encoded.groupby('outcode')['history_price'].transform('mean')

# Create a new column for the target encoded outcode
df_house_price_encoded['outcode_encoded'] = outcode_price_mean

# Drop the original outcode column
df_house_price_encoded = df_house_price_encoded.drop(columns=['outcode'])

# Display the first few rows with the new column and check info
display(df_house_price_encoded[['outcode_encoded', 'history_price']].head())
display(df_house_price_encoded.info())

   outcode_encoded  history_price
0     3.944857e+05         420000
1     5.076869e+05         355000
2     4.175679e+05         155000
3     1.560819e+06         830000
4     6.225024e+05         475000

<class 'pandas.core.frame.DataFrame'>
Index: 127594 entries, 0 to 137759
Data columns (total 40 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   bathrooms                            127594 non-null  float64
 1   bedrooms                             127594 non-null  float64
 2   floorAreaSqM                         127594 non-null  float64
 3   livingRooms                          127594 non-null  float64
 4   history_price                        127594 non-null  int64
 5   tenure_Feudal                        127594 non-null  bool
 6   tenure_Freehold                      127594 non-null  bool
 7   tenure_Leasehold                     127594 non-null  bool
 8   tenure_Missing                       127594 non-null  bool
 9   tenure_Shared                        127594 non-null  bool
 10  propertyType_Bungalow Property       127594 non-null  bool
 11  propertyType_Converted Flat          127594 non-null  bool
 12  propertyType_Detached Bungalow       127594 non-null  bool
 13  propertyType_Detached House          127594 non-null  bool
 14  propertyType_Detached Property       127594 non-null  bool
 15  propertyType_End Terrace Bungalow    127594 non-null  bool
 16  propertyType_End Terrace House       127594 non-null  bool
 17  propertyType_End Terrace Property    127594 non-null  bool
 18  propertyType_Flat/Maisonette         127594 non-null  bool
 19  propertyType_Mid Terrace Bungalow    127594 non-null  bool
 20  propertyType_Mid Terrace House       127594 non-null  bool
 21  propertyType_Mid Terrace Property    127594 non-null  bool
 22  propertyType_Missing                 127594 non-null  bool
 23  propertyType_Purpose Built Flat      127594 non-null  bool
 24  propertyType_Semi-Detached Bungalow  127594 non-null  bool
 25  propertyType_Semi-Detached House     127594 non-null  bool
 26  propertyType_Semi-Detached Property  127594 non-null  bool
 27  propertyType_Terrace Property        127594 non-null  bool
 28  propertyType_Terraced                127594 non-null  bool
 29  propertyType_Terraced Bungalow       127594 non-null  bool
 30  currentEnergyRating_A                127594 non-null  bool
 31  currentEnergyRating_B                127594 non-null  bool
 32  currentEnergyRating_C                127594 non-null  bool
 33  currentEnergyRating_D                127594 non-null  bool
 34  currentEnergyRating_E                127594 non-null  bool
 35  currentEnergyRating_F                127594 non-null  bool
 36  currentEnergyRating_G                127594 non-null  bool
 37  currentEnergyRating_Missing          127594 non-null  bool
 38  days_since_sold                      127594 non-null  int64
 39  outcode_encoded                      127594 non-null  float64
dtypes: bool(33), float64(5), int64(2)
memory usage: 11.8 MB

None

In [ ]:
df_house_price_encoded = df_house_price_encoded.drop(columns=['postcode'])

print(df_house_price_encoded.columns.tolist())

['outcode', 'bathrooms', 'bedrooms', 'floorAreaSqM', 'livingRooms', 'history_price', 'tenure_Feudal', 'tenure_Freehold', 'tenure_Leasehold', 'tenure_Missing', 'tenure_Shared', 'propertyType_Bungalow Property', 'propertyType_Converted Flat', 'propertyType_Detached Bungalow', 'propertyType_Detached House', 'propertyType_Detached Property', 'propertyType_End Terrace Bungalow', 'propertyType_End Terrace House', 'propertyType_End Terrace Property', 'propertyType_Flat/Maisonette', 'propertyType_Mid Terrace Bungalow', 'propertyType_Mid Terrace House', 'propertyType_Mid Terrace Property', 'propertyType_Missing', 'propertyType_Purpose Built Flat', 'propertyType_Semi-Detached Bungalow', 'propertyType_Semi-Detached House', 'propertyType_Semi-Detached Property', 'propertyType_Terrace Property', 'propertyType_Terraced', 'propertyType_Terraced Bungalow', 'currentEnergyRating_A', 'currentEnergyRating_B', 'currentEnergyRating_C', 'currentEnergyRating_D', 'currentEnergyRating_E', 'currentEnergyRating_F', 'currentEnergyRating_G', 'currentEnergyRating_Missing', 'days_since_sold']

In [ ]:
columns_to_drop = ['fullAddress', 'country', 'history_date']
df_house_price_encoded = df_house_price_encoded.drop(columns=columns_to_drop)

print(df_house_price_encoded.columns.tolist())

['postcode', 'outcode', 'bathrooms', 'bedrooms', 'floorAreaSqM', 'livingRooms', 'history_price', 'tenure_Feudal', 'tenure_Freehold', 'tenure_Leasehold', 'tenure_Missing', 'tenure_Shared', 'propertyType_Bungalow Property', 'propertyType_Converted Flat', 'propertyType_Detached Bungalow', 'propertyType_Detached House', 'propertyType_Detached Property', 'propertyType_End Terrace Bungalow', 'propertyType_End Terrace House', 'propertyType_End Terrace Property', 'propertyType_Flat/Maisonette', 'propertyType_Mid Terrace Bungalow', 'propertyType_Mid Terrace House', 'propertyType_Mid Terrace Property', 'propertyType_Missing', 'propertyType_Purpose Built Flat', 'propertyType_Semi-Detached Bungalow', 'propertyType_Semi-Detached House', 'propertyType_Semi-Detached Property', 'propertyType_Terrace Property', 'propertyType_Terraced', 'propertyType_Terraced Bungalow', 'currentEnergyRating_A', 'currentEnergyRating_B', 'currentEnergyRating_C', 'currentEnergyRating_D', 'currentEnergyRating_E', 'currentEnergyRating_F', 'currentEnergyRating_G', 'currentEnergyRating_Missing', 'days_since_sold']

In [ ]:
print(df_house_price_encoded.columns.tolist())

['fullAddress', 'postcode', 'country', 'outcode', 'bathrooms', 'bedrooms', 'floorAreaSqM', 'livingRooms', 'history_date', 'history_price', 'tenure_Feudal', 'tenure_Freehold', 'tenure_Leasehold', 'tenure_Missing', 'tenure_Shared', 'propertyType_Bungalow Property', 'propertyType_Converted Flat', 'propertyType_Detached Bungalow', 'propertyType_Detached House', 'propertyType_Detached Property', 'propertyType_End Terrace Bungalow', 'propertyType_End Terrace House', 'propertyType_End Terrace Property', 'propertyType_Flat/Maisonette', 'propertyType_Mid Terrace Bungalow', 'propertyType_Mid Terrace House', 'propertyType_Mid Terrace Property', 'propertyType_Missing', 'propertyType_Purpose Built Flat', 'propertyType_Semi-Detached Bungalow', 'propertyType_Semi-Detached House', 'propertyType_Semi-Detached Property', 'propertyType_Terrace Property', 'propertyType_Terraced', 'propertyType_Terraced Bungalow', 'currentEnergyRating_A', 'currentEnergyRating_B', 'currentEnergyRating_C', 'currentEnergyRating_D', 'currentEnergyRating_E', 'currentEnergyRating_F', 'currentEnergyRating_G', 'currentEnergyRating_Missing', 'days_since_sold']

In [ ]:
display(df_house_price_encoded.head(20))

,bathrooms,bedrooms,floorAreaSqM,livingRooms,history_price,tenure_Feudal,tenure_Freehold,tenure_Leasehold,tenure_Missing,tenure_Shared,...,currentEnergyRating_A,currentEnergyRating_B,currentEnergyRating_C,currentEnergyRating_D,currentEnergyRating_E,currentEnergyRating_F,currentEnergyRating_G,currentEnergyRating_Missing,days_since_sold,outcode_encoded
0,2.0,4.0,138.0,1.0,420000,False,True,False,False,False,...,False,False,True,False,False,False,False,False,936,3.944857e+05
1,1.0,1.0,41.0,1.0,355000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,2051,5.076869e+05
2,1.0,2.0,77.0,1.0,155000,False,False,True,False,False,...,False,False,True,False,False,False,False,False,1212,4.175679e+05
3,1.0,4.0,115.0,1.0,830000,False,True,False,False,False,...,False,False,True,False,False,False,False,False,1272,1.560819e+06
4,1.0,3.0,85.0,1.0,475000,False,False,True,False,False,...,False,False,False,True,False,False,False,False,855,6.225024e+05
5,1.0,2.0,85.0,2.0,400000,False,True,False,False,False,...,False,False,False,False,False,False,False,True,1419,4.358907e+05
6,2.0,3.0,124.0,2.0,850000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,589,1.097159e+06
7,1.0,2.0,71.0,1.0,388000,False,False,True,False,False,...,False,False,False,True,False,False,False,False,1455,6.503107e+05
9,1.0,1.0,40.0,1.0,218000,False,False,True,False,False,...,False,False,True,False,False,False,False,False,1170,3.733273e+05
10,1.0,4.0,146.0,2.0,910000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,1027,6.187392e+05
11,1.0,2.0,189.0,1.0,1030000,False,True,False,False,False,...,False,True,False,False,False,False,False,False,1629,8.955796e+05
13,1.0,2.0,54.0,1.0,350000,False,False,True,False,False,...,False,False,False,True,False,False,False,False,764,6.225024e+05
14,1.0,3.0,116.0,2.0,980000,False,True,False,False,False,...,False,False,True,False,False,False,False,False,384,5.235048e+05
15,2.0,2.0,112.0,2.0,640000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,1371,6.175652e+05
16,1.0,2.0,108.0,3.0,550000,False,True,False,False,False,...,False,False,False,False,True,False,False,False,1133,4.924437e+05
17,1.0,2.0,66.0,1.0,573442,False,False,True,False,False,...,False,False,True,False,False,False,False,False,1794,9.458508e+05
18,2.0,4.0,187.0,2.0,2530000,False,True,False,False,False,...,False,False,False,False,False,False,False,True,1633,7.971884e+05
19,1.0,3.0,140.0,1.0,1200000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,1535,7.971884e+05
20,1.0,1.0,82.0,1.0,765000,False,False,True,False,False,...,False,False,False,False,True,False,False,False,1133,8.546752e+05
21,2.0,4.0,129.0,1.0,790000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,1615,5.240281e+05

In [ ]:
from datetime import datetime

# Define a reference date (e.g., today's date)
reference_date = datetime.now()

# Calculate 'days_since_sold'
df_house_price_encoded['days_since_sold'] = (reference_date - df_house_price_encoded['history_date']).dt.days

# Display the first few rows with the new column
display(df_house_price_encoded[['history_date', 'days_since_sold']].head())
display(df_house_price_encoded.info())

  history_date  days_since_sold
0   2023-02-17              936
1   2020-01-29             2051
2   2022-05-17             1212
3   2022-03-18             1272
4   2023-05-09              855

<class 'pandas.core.frame.DataFrame'>
Index: 127594 entries, 0 to 137759
Data columns (total 44 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   fullAddress                          127594 non-null  object
 1   postcode                             127594 non-null  object
 2   country                              127594 non-null  object
 3   outcode                              127594 non-null  object
 4   bathrooms                            127594 non-null  float64
 5   bedrooms                             127594 non-null  float64
 6   floorAreaSqM                         127594 non-null  float64
 7   livingRooms                          127594 non-null  float64
 8   history_date                         127594 non-null  datetime64[ns]
 9   history_price                        127594 non-null  int64
 10  tenure_Feudal                        127594 non-null  bool
 11  tenure_Freehold                      127594 non-null  bool
 12  tenure_Leasehold                     127594 non-null  bool
 13  tenure_Missing                       127594 non-null  bool
 14  tenure_Shared                        127594 non-null  bool
 15  propertyType_Bungalow Property       127594 non-null  bool
 16  propertyType_Converted Flat          127594 non-null  bool
 17  propertyType_Detached Bungalow       127594 non-null  bool
 18  propertyType_Detached House          127594 non-null  bool
 19  propertyType_Detached Property       127594 non-null  bool
 20  propertyType_End Terrace Bungalow    127594 non-null  bool
 21  propertyType_End Terrace House       127594 non-null  bool
 22  propertyType_End Terrace Property    127594 non-null  bool
 23  propertyType_Flat/Maisonette         127594 non-null  bool
 24  propertyType_Mid Terrace Bungalow    127594 non-null  bool
 25  propertyType_Mid Terrace House       127594 non-null  bool
 26  propertyType_Mid Terrace Property    127594 non-null  bool
 27  propertyType_Missing                 127594 non-null  bool
 28  propertyType_Purpose Built Flat      127594 non-null  bool
 29  propertyType_Semi-Detached Bungalow  127594 non-null  bool
 30  propertyType_Semi-Detached House     127594 non-null  bool
 31  propertyType_Semi-Detached Property  127594 non-null  bool
 32  propertyType_Terrace Property        127594 non-null  bool
 33  propertyType_Terraced                127594 non-null  bool
 34  propertyType_Terraced Bungalow       127594 non-null  bool
 35  currentEnergyRating_A                127594 non-null  bool
 36  currentEnergyRating_B                127594 non-null  bool
 37  currentEnergyRating_C                127594 non-null  bool
 38  currentEnergyRating_D                127594 non-null  bool
 39  currentEnergyRating_E                127594 non-null  bool
 40  currentEnergyRating_F                127594 non-null  bool
 41  currentEnergyRating_G                127594 non-null  bool
 42  currentEnergyRating_Missing          127594 non-null  bool
 43  days_since_sold                      127594 non-null  int64
dtypes: bool(33), datetime64[ns](1), float64(4), int64(2), object(4)
memory usage: 15.7+ MB

None

In [ ]:
display(df_house_price_encoded.isnull().sum())

bathrooms                              0
bedrooms                               0
floorAreaSqM                           0
livingRooms                            0
history_price                          0
tenure_Feudal                          0
tenure_Freehold                        0
tenure_Leasehold                       0
tenure_Missing                         0
tenure_Shared                          0
propertyType_Bungalow Property         0
propertyType_Converted Flat            0
propertyType_Detached Bungalow         0
propertyType_Detached House            0
propertyType_Detached Property         0
propertyType_End Terrace Bungalow      0
propertyType_End Terrace House         0
propertyType_End Terrace Property      0
propertyType_Flat/Maisonette           0
propertyType_Mid Terrace Bungalow      0
propertyType_Mid Terrace House         0
propertyType_Mid Terrace Property      0
propertyType_Missing                   0
propertyType_Purpose Built Flat        0
propertyType_Semi-Detached Bungalow    0
propertyType_Semi-Detached House       0
propertyType_Semi-Detached Property    0
propertyType_Terrace Property          0
propertyType_Terraced                  0
propertyType_Terraced Bungalow         0
currentEnergyRating_A                  0
currentEnergyRating_B                  0
currentEnergyRating_C                  0
currentEnergyRating_D                  0
currentEnergyRating_E                  0
currentEnergyRating_F                  0
currentEnergyRating_G                  0
currentEnergyRating_Missing            0
days_since_sold                        0
outcode_encoded                        0
dtype: int64

In [ ]:
categorical_columns = ['tenure', 'propertyType', 'currentEnergyRating']

# Perform one-hot encoding
df_house_price_encoded = pd.get_dummies(df_house_price, columns=categorical_columns, dummy_na=False)

# Drop irrelevant columns after one-hot encoding, except for history_date for now
columns_to_drop_after_encoding = ['fullAddress', 'country']
df_house_price_encoded = df_house_price_encoded.drop(columns=columns_to_drop_after_encoding)

# Target encode 'outcode' and drop the original 'outcode' column
outcode_price_mean = df_house_price_encoded.groupby('outcode')['history_price'].transform('mean')
df_house_price_encoded['outcode_encoded'] = outcode_price_mean
df_house_price_encoded = df_house_price_encoded.drop(columns=['outcode'])

# Calculate days since sold
from datetime import datetime
reference_date = datetime.now()
df_house_price_encoded['days_since_sold'] = (reference_date - df_house_price_encoded['history_date']).dt.days

# Now drop the original history_date column
df_house_price_encoded = df_house_price_encoded.drop(columns=['history_date'])


display(df_house_price_encoded.head())
display(df_house_price_encoded.info())

,postcode,bathrooms,bedrooms,floorAreaSqM,livingRooms,history_price,tenure_Feudal,tenure_Freehold,tenure_Leasehold,tenure_Missing,...,currentEnergyRating_A,currentEnergyRating_B,currentEnergyRating_C,currentEnergyRating_D,currentEnergyRating_E,currentEnergyRating_F,currentEnergyRating_G,currentEnergyRating_Missing,outcode_encoded,days_since_sold
0,E6 5TX,2.0,4.0,138.0,1.0,420000,False,True,False,False,...,False,False,True,False,False,False,False,False,3.944857e+05,936
1,SE16 3RQ,1.0,1.0,41.0,1.0,355000,False,True,False,False,...,False,False,False,True,False,False,False,False,5.076869e+05,2051
2,N17 8HE,1.0,2.0,77.0,1.0,155000,False,False,True,False,...,False,False,True,False,False,False,False,False,4.175679e+05,1212
3,N6 4BF,1.0,4.0,115.0,1.0,830000,False,True,False,False,...,False,False,True,False,False,False,False,False,1.560819e+06,1272
4,SE11 4HP,1.0,3.0,85.0,1.0,475000,False,False,True,False,...,False,False,False,True,False,False,False,False,6.225024e+05,855

<class 'pandas.core.frame.DataFrame'>
Index: 127594 entries, 0 to 137759
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   postcode                             127594 non-null  object
 1   bathrooms                            127594 non-null  float64
 2   bedrooms                             127594 non-null  float64
 3   floorAreaSqM                         127594 non-null  float64
 4   livingRooms                          127594 non-null  float64
 5   history_price                        127594 non-null  int64
 6   tenure_Feudal                        127594 non-null  bool
 7   tenure_Freehold                      127594 non-null  bool
 8   tenure_Leasehold                     127594 non-null  bool
 9   tenure_Missing                       127594 non-null  bool
 10  tenure_Shared                        127594 non-null  bool
 11  propertyType_Bungalow Property       127594 non-null  bool
 12  propertyType_Converted Flat          127594 non-null  bool
 13  propertyType_Detached Bungalow       127594 non-null  bool
 14  propertyType_Detached House          127594 non-null  bool
 15  propertyType_Detached Property       127594 non-null  bool
 16  propertyType_End Terrace Bungalow    127594 non-null  bool
 17  propertyType_End Terrace House       127594 non-null  bool
 18  propertyType_End Terrace Property    127594 non-null  bool
 19  propertyType_Flat/Maisonette         127594 non-null  bool
 20  propertyType_Mid Terrace Bungalow    127594 non-null  bool
 21  propertyType_Mid Terrace House       127594 non-null  bool
 22  propertyType_Mid Terrace Property    127594 non-null  bool
 23  propertyType_Missing                 127594 non-null  bool
 24  propertyType_Purpose Built Flat      127594 non-null  bool
 25  propertyType_Semi-Detached Bungalow  127594 non-null  bool
 26  propertyType_Semi-Detached House     127594 non-null  bool
 27  propertyType_Semi-Detached Property  127594 non-null  bool
 28  propertyType_Terrace Property        127594 non-null  bool
 29  propertyType_Terraced                127594 non-null  bool
 30  propertyType_Terraced Bungalow       127594 non-null  bool
 31  currentEnergyRating_A                127594 non-null  bool
 32  currentEnergyRating_B                127594 non-null  bool
 33  currentEnergyRating_C                127594 non-null  bool
 34  currentEnergyRating_D                127594 non-null  bool
 35  currentEnergyRating_E                127594 non-null  bool
 36  currentEnergyRating_F                127594 non-null  bool
 37  currentEnergyRating_G                127594 non-null  bool
 38  currentEnergyRating_Missing          127594 non-null  bool
 39  outcode_encoded                      127594 non-null  float64
 40  days_since_sold                      127594 non-null  int64
dtypes: bool(33), float64(5), int64(2), object(1)
memory usage: 12.8+ MB

None

In [ ]:
columns_to_impute_categorical = ['tenure', 'propertyType', 'currentEnergyRating']

for col in columns_to_impute_categorical:
    df_house_price[col] = df_house_price[col].fillna('Missing')

display(df_house_price.info())

<class 'pandas.core.frame.DataFrame'>
Index: 127594 entries, 0 to 137759
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fullAddress          127594 non-null  object
 1   postcode             127594 non-null  object
 2   country              127594 non-null  object
 3   outcode              127594 non-null  object
 4   bathrooms            127594 non-null  float64
 5   bedrooms             127594 non-null  float64
 6   floorAreaSqM         127594 non-null  float64
 7   livingRooms          127594 non-null  float64
 8   tenure               127594 non-null  object
 9   propertyType         127594 non-null  object
 10  currentEnergyRating  127594 non-null  object
 11  history_date         127594 non-null  datetime64[ns]
 12  history_price        127594 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 13.6+ MB

None

In [ ]:
display(df_house_price_encoded.head())

,bathrooms,bedrooms,floorAreaSqM,livingRooms,history_price,tenure_Feudal,tenure_Freehold,tenure_Leasehold,tenure_Missing,tenure_Shared,...,currentEnergyRating_A,currentEnergyRating_B,currentEnergyRating_C,currentEnergyRating_D,currentEnergyRating_E,currentEnergyRating_F,currentEnergyRating_G,currentEnergyRating_Missing,outcode_encoded,days_since_sold
0,2.0,4.0,138.0,1.0,420000,False,True,False,False,False,...,False,False,True,False,False,False,False,False,3.944857e+05,936
1,1.0,1.0,41.0,1.0,355000,False,True,False,False,False,...,False,False,False,True,False,False,False,False,5.076869e+05,2051
2,1.0,2.0,77.0,1.0,155000,False,False,True,False,False,...,False,False,True,False,False,False,False,False,4.175679e+05,1212
3,1.0,4.0,115.0,1.0,830000,False,True,False,False,False,...,False,False,True,False,False,False,False,False,1.560819e+06,1272
4,1.0,3.0,85.0,1.0,475000,False,False,True,False,False,...,False,False,False,True,False,False,False,False,6.225024e+05,855

In [ ]:
# Save the DataFrame to an Excel file
output_filename = 'final_housing_data.xlsx'
df_house_price_encoded.to_excel(output_filename, index=False)

print(f"DataFrame successfully saved to '{output_filename}'")

DataFrame successfully saved to 'final_housing_data.xlsx'